// Barrel do pacote compartilhado — tipos (contrato de exibição) + constantes
// dos enums de workspace (STAGE_NAMES, PRIORITIES).
export type {
  Status,
  Level,
  RouteCoord,
  Repository,
  EpicSummary,
  RepositoryEpics,
  Person,
  ChildItem,
  MetaField,
  Crumb,
  WorkItemView,
  WorkItemPatch,
  CreateRepositoryRequest,
  UpdateRepositoryRequest,
  CreateFeatureRequest,
  ArtifactKind,
  ArtifactRefineRequest,
  ArtifactRefineResponse,
  ArtifactSaveRequest,
  WorkspaceRole,
  StageName,
  Priority,
  MilestoneSummary,
  PullRequestRef,
  SnapshotItem,
  ProjectSnapshot,
} from './types';
export { STAGE_NAMES, PRIORITIES } from './types';
